server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flower_shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 3.8757845
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  # 使用 Base64 编码的密钥（示例值，请替换为安全随机值）
  secret: ZmFzdF9kZXZfYmFzZTY0X3NlY3JldF9zaGFyZWRfa2V5X2Zvcl9qc3V0
  expire-seconds: 3600

app:
  upload:
    # 文件上传保存的本地目录，相对于应用启动目录
    dir: uploads